package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private State state;
     private String city;
     private Set owners = new HashSet(0);

    public City() {
    }

	
    public City(State state) {
        this.state = state;
    }
    public City(State state, String city, Set owners) {
       this.state = state;
       this.city = city;
       this.owners = owners;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }




}


