package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Claim generated by hbm2java
 */
public class Claim  implements java.io.Serializable {


     private Integer claimId;
     private ClaimStatus claimStatus;
     private Company company;
     private Vehicle vehicle;
     private Double longitude;
     private Double latitude;
     private Date datetime;
     private Set paybacks = new HashSet(0);
     private Set claimPhotos = new HashSet(0);

    public Claim() {
    }

	
    public Claim(ClaimStatus claimStatus, Company company, Vehicle vehicle) {
        this.claimStatus = claimStatus;
        this.company = company;
        this.vehicle = vehicle;
    }
    public Claim(ClaimStatus claimStatus, Company company, Vehicle vehicle, Double longitude, Double latitude, Date datetime, Set paybacks, Set claimPhotos) {
       this.claimStatus = claimStatus;
       this.company = company;
       this.vehicle = vehicle;
       this.longitude = longitude;
       this.latitude = latitude;
       this.datetime = datetime;
       this.paybacks = paybacks;
       this.claimPhotos = claimPhotos;
    }
   
    public Integer getClaimId() {
        return this.claimId;
    }
    
    public void setClaimId(Integer claimId) {
        this.claimId = claimId;
    }
    public ClaimStatus getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(ClaimStatus claimStatus) {
        this.claimStatus = claimStatus;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Set getPaybacks() {
        return this.paybacks;
    }
    
    public void setPaybacks(Set paybacks) {
        this.paybacks = paybacks;
    }
    public Set getClaimPhotos() {
        return this.claimPhotos;
    }
    
    public void setClaimPhotos(Set claimPhotos) {
        this.claimPhotos = claimPhotos;
    }




}


