package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;
     private String companyLogin;
     private String password;
     private Set claims = new HashSet(0);

    public Company() {
    }

    public Company(String companyName, String companyLogin, String password, Set claims) {
       this.companyName = companyName;
       this.companyLogin = companyLogin;
       this.password = password;
       this.claims = claims;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyLogin() {
        return this.companyLogin;
    }
    
    public void setCompanyLogin(String companyLogin) {
        this.companyLogin = companyLogin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getClaims() {
        return this.claims;
    }
    
    public void setClaims(Set claims) {
        this.claims = claims;
    }




}


