package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FuelType generated by hbm2java
 */
public class FuelType  implements java.io.Serializable {


     private Integer fuelTypeId;
     private String fuelType;
     private Set vehicles = new HashSet(0);

    public FuelType() {
    }

    public FuelType(String fuelType, Set vehicles) {
       this.fuelType = fuelType;
       this.vehicles = vehicles;
    }
   
    public Integer getFuelTypeId() {
        return this.fuelTypeId;
    }
    
    public void setFuelTypeId(Integer fuelTypeId) {
        this.fuelTypeId = fuelTypeId;
    }
    public String getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


