package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ImageUrl generated by hbm2java
 */
public class ImageUrl  implements java.io.Serializable {


     private Integer imageUrlId;
     private String imageUrl;
     private Set owners = new HashSet(0);
     private Set vehicles = new HashSet(0);

    public ImageUrl() {
    }

    public ImageUrl(String imageUrl, Set owners, Set vehicles) {
       this.imageUrl = imageUrl;
       this.owners = owners;
       this.vehicles = vehicles;
    }
   
    public Integer getImageUrlId() {
        return this.imageUrlId;
    }
    
    public void setImageUrlId(Integer imageUrlId) {
        this.imageUrlId = imageUrlId;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Set getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set owners) {
        this.owners = owners;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


