package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuranceStatus generated by hbm2java
 */
public class InsuranceStatus  implements java.io.Serializable {


     private Integer insuranceStatusId;
     private String insuranceStatus;
     private Set insuranceInfos = new HashSet(0);

    public InsuranceStatus() {
    }

    public InsuranceStatus(String insuranceStatus, Set insuranceInfos) {
       this.insuranceStatus = insuranceStatus;
       this.insuranceInfos = insuranceInfos;
    }
   
    public Integer getInsuranceStatusId() {
        return this.insuranceStatusId;
    }
    
    public void setInsuranceStatusId(Integer insuranceStatusId) {
        this.insuranceStatusId = insuranceStatusId;
    }
    public String getInsuranceStatus() {
        return this.insuranceStatus;
    }
    
    public void setInsuranceStatus(String insuranceStatus) {
        this.insuranceStatus = insuranceStatus;
    }
    public Set getInsuranceInfos() {
        return this.insuranceInfos;
    }
    
    public void setInsuranceInfos(Set insuranceInfos) {
        this.insuranceInfos = insuranceInfos;
    }




}


