package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InsuranceInfo generated by hbm2java
 */
public class InsuranceInfo  implements java.io.Serializable {


     private Integer insuranceId;
     private InsuranceStatus insuranceStatus;
     private Owner owner;
     private Vehicle vehicle;
     private Double insuredValue;
     private Date insuredDate;
     private Date expireDate;

    public InsuranceInfo() {
    }

	
    public InsuranceInfo(InsuranceStatus insuranceStatus, Owner owner, Vehicle vehicle) {
        this.insuranceStatus = insuranceStatus;
        this.owner = owner;
        this.vehicle = vehicle;
    }
    public InsuranceInfo(InsuranceStatus insuranceStatus, Owner owner, Vehicle vehicle, Double insuredValue, Date insuredDate, Date expireDate) {
       this.insuranceStatus = insuranceStatus;
       this.owner = owner;
       this.vehicle = vehicle;
       this.insuredValue = insuredValue;
       this.insuredDate = insuredDate;
       this.expireDate = expireDate;
    }
   
    public Integer getInsuranceId() {
        return this.insuranceId;
    }
    
    public void setInsuranceId(Integer insuranceId) {
        this.insuranceId = insuranceId;
    }
    public InsuranceStatus getInsuranceStatus() {
        return this.insuranceStatus;
    }
    
    public void setInsuranceStatus(InsuranceStatus insuranceStatus) {
        this.insuranceStatus = insuranceStatus;
    }
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Double getInsuredValue() {
        return this.insuredValue;
    }
    
    public void setInsuredValue(Double insuredValue) {
        this.insuredValue = insuredValue;
    }
    public Date getInsuredDate() {
        return this.insuredDate;
    }
    
    public void setInsuredDate(Date insuredDate) {
        this.insuredDate = insuredDate;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }




}


