package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payback generated by hbm2java
 */
public class Payback  implements java.io.Serializable {


     private Integer paybackId;
     private Claim claim;
     private Date dateTime;
     private Double amount;
     private String description;

    public Payback() {
    }

	
    public Payback(Claim claim) {
        this.claim = claim;
    }
    public Payback(Claim claim, Date dateTime, Double amount, String description) {
       this.claim = claim;
       this.dateTime = dateTime;
       this.amount = amount;
       this.description = description;
    }
   
    public Integer getPaybackId() {
        return this.paybackId;
    }
    
    public void setPaybackId(Integer paybackId) {
        this.paybackId = paybackId;
    }
    public Claim getClaim() {
        return this.claim;
    }
    
    public void setClaim(Claim claim) {
        this.claim = claim;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


