package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleModel generated by hbm2java
 */
public class VehicleModel  implements java.io.Serializable {


     private Integer vehicleModelId;
     private VehicleBrand vehicleBrand;
     private String vehicleModel;
     private Set vehicles = new HashSet(0);

    public VehicleModel() {
    }

	
    public VehicleModel(VehicleBrand vehicleBrand) {
        this.vehicleBrand = vehicleBrand;
    }
    public VehicleModel(VehicleBrand vehicleBrand, String vehicleModel, Set vehicles) {
       this.vehicleBrand = vehicleBrand;
       this.vehicleModel = vehicleModel;
       this.vehicles = vehicles;
    }
   
    public Integer getVehicleModelId() {
        return this.vehicleModelId;
    }
    
    public void setVehicleModelId(Integer vehicleModelId) {
        this.vehicleModelId = vehicleModelId;
    }
    public VehicleBrand getVehicleBrand() {
        return this.vehicleBrand;
    }
    
    public void setVehicleBrand(VehicleBrand vehicleBrand) {
        this.vehicleBrand = vehicleBrand;
    }
    public String getVehicleModel() {
        return this.vehicleModel;
    }
    
    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


