package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private String vehicleId;
     private Color color;
     private FuelType fuelType;
     private ImageUrl imageUrl;
     private VehicleModel vehicleModel;
     private VehicleStatus vehicleStatus;
     private String enginNo;
     private String chasisNo;
     private Integer year;
     private Integer noOfSeats;
     private Integer noOfDoors;
     private Double enginCapacity;
     private Set claims = new HashSet(0);
     private Set insuranceInfos = new HashSet(0);

    public Vehicle() {
    }

	
    public Vehicle(String vehicleId, Color color, FuelType fuelType, ImageUrl imageUrl, VehicleModel vehicleModel, VehicleStatus vehicleStatus) {
        this.vehicleId = vehicleId;
        this.color = color;
        this.fuelType = fuelType;
        this.imageUrl = imageUrl;
        this.vehicleModel = vehicleModel;
        this.vehicleStatus = vehicleStatus;
    }
    public Vehicle(String vehicleId, Color color, FuelType fuelType, ImageUrl imageUrl, VehicleModel vehicleModel, VehicleStatus vehicleStatus, String enginNo, String chasisNo, Integer year, Integer noOfSeats, Integer noOfDoors, Double enginCapacity, Set claims, Set insuranceInfos) {
       this.vehicleId = vehicleId;
       this.color = color;
       this.fuelType = fuelType;
       this.imageUrl = imageUrl;
       this.vehicleModel = vehicleModel;
       this.vehicleStatus = vehicleStatus;
       this.enginNo = enginNo;
       this.chasisNo = chasisNo;
       this.year = year;
       this.noOfSeats = noOfSeats;
       this.noOfDoors = noOfDoors;
       this.enginCapacity = enginCapacity;
       this.claims = claims;
       this.insuranceInfos = insuranceInfos;
    }
   
    public String getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public FuelType getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(FuelType fuelType) {
        this.fuelType = fuelType;
    }
    public ImageUrl getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(ImageUrl imageUrl) {
        this.imageUrl = imageUrl;
    }
    public VehicleModel getVehicleModel() {
        return this.vehicleModel;
    }
    
    public void setVehicleModel(VehicleModel vehicleModel) {
        this.vehicleModel = vehicleModel;
    }
    public VehicleStatus getVehicleStatus() {
        return this.vehicleStatus;
    }
    
    public void setVehicleStatus(VehicleStatus vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }
    public String getEnginNo() {
        return this.enginNo;
    }
    
    public void setEnginNo(String enginNo) {
        this.enginNo = enginNo;
    }
    public String getChasisNo() {
        return this.chasisNo;
    }
    
    public void setChasisNo(String chasisNo) {
        this.chasisNo = chasisNo;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getNoOfSeats() {
        return this.noOfSeats;
    }
    
    public void setNoOfSeats(Integer noOfSeats) {
        this.noOfSeats = noOfSeats;
    }
    public Integer getNoOfDoors() {
        return this.noOfDoors;
    }
    
    public void setNoOfDoors(Integer noOfDoors) {
        this.noOfDoors = noOfDoors;
    }
    public Double getEnginCapacity() {
        return this.enginCapacity;
    }
    
    public void setEnginCapacity(Double enginCapacity) {
        this.enginCapacity = enginCapacity;
    }
    public Set getClaims() {
        return this.claims;
    }
    
    public void setClaims(Set claims) {
        this.claims = claims;
    }
    public Set getInsuranceInfos() {
        return this.insuranceInfos;
    }
    
    public void setInsuranceInfos(Set insuranceInfos) {
        this.insuranceInfos = insuranceInfos;
    }




}


