package model;
// Generated May 7, 2017 10:50:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleStatus generated by hbm2java
 */
public class VehicleStatus  implements java.io.Serializable {


     private Integer vehicleStatusId;
     private String vehicleStatus;
     private Set vehicles = new HashSet(0);

    public VehicleStatus() {
    }

    public VehicleStatus(String vehicleStatus, Set vehicles) {
       this.vehicleStatus = vehicleStatus;
       this.vehicles = vehicles;
    }
   
    public Integer getVehicleStatusId() {
        return this.vehicleStatusId;
    }
    
    public void setVehicleStatusId(Integer vehicleStatusId) {
        this.vehicleStatusId = vehicleStatusId;
    }
    public String getVehicleStatus() {
        return this.vehicleStatus;
    }
    
    public void setVehicleStatus(String vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


